#include <stdio.h>
/**
 * main - entry point
 *
 * program that finds and prints the sum of the even-valued terms, followed by a new line.
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
 *
 * Return: 0
 */
int main() {
    int first = 1, second = 2, next, sum = 0;

    while (second <= 4000000) {
        if (second % 2 == 0) {
            sum += second;
        }

        next = first + second;
        first = second;
        second = next;
    }

    printf("Sum of even-valued terms in Fibonacci sequence: %d\n", sum);

    return 0;
}
